project:
  type: website
  post-render:
    - "rsync -av static/. _site/"

website:
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      #- teaching.qmd
  site-url: https://jvkersch.github.io/

format:
  html:
    theme: litera
    css: styles.css



